# Enable UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# Enable TCP syslog reception
module(load="imtcp")
input(type="imtcp" port="514")

# Template for service-specific log files
template(name="RemoteLogFile" type="string" string="/var/log/%HOSTNAME%/mail.log")

# Route logs from different hosts to different files
if $hostname == 'mx' then {
    action(type="omfile" file="/var/log/mx/mail.log")
    stop
}

if $hostname == 'mailer1' then {
    action(type="omfile" file="/var/log/mailer1/mail.log")
    stop
}

if $hostname == 'mailer2' then {
    action(type="omfile" file="/var/log/mailer2/mail.log")
    stop
}

if $hostname == 'mailer3' then {
    action(type="omfile" file="/var/log/mailer3/mail.log")
    stop
}

if $hostname == 'mailpolicy1' then {
    action(type="omfile" file="/var/log/mailpolicy1/mail.log")
    stop
}

if $hostname == 'mailpolicy2' then {
    action(type="omfile" file="/var/log/mailpolicy2/mail.log")
    stop
}

if $hostname == 'mailpolicy3' then {
    action(type="omfile" file="/var/log/mailpolicy3/mail.log")
    stop
}

if $hostname == 'mailbox' then {
    action(type="omfile" file="/var/log/mailbox/mail.log")
    stop
}
